id: 98f4b91faa734de4af78cb855e439154
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_182-The_Perfection_of_Generosity-v2
  language: en
  author: ''
  volume: {}
